name: fitup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter: # Required for every Flutter project
    sdk: flutter # Required for every Flutter project

  cupertino_icons: ^1.0.2 # Only required if you use Cupertino (iOS style) icons

  #Firebase
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  firebase_storage: ^10.2.9

  image_picker: ^0.8.4+11
  flutter_launcher_icons: "^0.9.2"
  intl: ^0.17.0
  flutter_lints: ^1.0.4
  integration_test: 
    sdk: flutter
    version: ^0.0.0

  provider: ^6.0.2

  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
  flutter_native_timezone: ^2.0.0
  video_player: ^2.3.0
  uuid: ^3.0.6
  flutter_speed_dial: ^5.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_screenutil: ^5.4.0+1
  shared_preferences: ^2.0.13


  

flutter:
  uses-material-design: true # Required if you use the Material icon font
  assets:
    - assets/images/
    - assets/icons/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies: 
  test: ^1.19.0
  mockito: ^5.1.0
